export const FIELDS = {
    FIRST_NAME: "First name",
    LAST_NAME: "Last name",
    EMAIL: "Email",
    PHONE: "Phone number",
    USERNAME: "Username",
    PASSWORD: "Password",
    SECURITY_QUESTION: "Security question",
    SECURITY_ANSWER: "Security answer",
    REFRESH_TOKEN: "Refresh token",

    USER_ID: "User ID",
    CUSTOMER_STATUS: "Customer status",
    TEMPORARY_CUSTOMER_ID: "Temporary Customer ID",
    HAVMOR_PLATFORM_CUSTOMER_ID: "Havmor Platform Customer ID",
    SHOP_NAME: "Shop name",
    PAN_CARD_NUMBER: "PAN Card number",
    GSTIN_NUMBER: "GSTIN number",
    CUSTOMER_ADDRESS: "Customer address",

    PLACE: "Place",
    CITY: "City",
    INDIAN_STATE: "State",
    INDIAN_STATE_CODE: "State code",
    PIN_CODE: "PIN code",

    IS_ACTIVE: "Active Status",

    PRODUCT_CATEGORY: "Product Category",
    PRODUCT_CATEGORY_CODE: "Product Category Code",
    PRODUCT_PACK_SIZE: "Product Pack Size",
    PRODUCT_VOLUME_UNIT: "Product Volume unit",

    PRODUCT_NAME: "Product name",
    VOLUME_MAGNITUDE: "Volume magnitude",
    MATERIAL_CODE: "Material code",
    MRP: "MRP (Maximum Retail Price)",
    RATE: "Rate",
    STOCK: "Stock",
    HSN_CODE: "HSN code",
};
